# Generated by Django 4.2.13 on 2025-08-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbottext',
            name='language',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='core.language'),
        ),
    ]
