# Generated by Django 4.2.13 on 2025-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(null=True, to='partners.product'),
        ),
    ]
