# Generated by Django 4.2.13 on 2025-08-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_id', models.CharField(max_length=100)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('C', 'Completed'), ('X', 'Rejected')], max_length=1)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_location_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_location_long', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_time_avarage', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('discounted_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('C', 'Completed'), ('X', 'Rejected')], default='P', max_length=1)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_cart', to='partners.product')),
            ],
        ),
    ]
